---
- name: Join to master node
  hosts: workers
  become: yes
  remote_user: ubuntu

  tasks:
  - name: Join
    ansible.builtin.shell: kubeadm join 10.2.3.8:6443 --token wucqvd.3a610ve09wwg3rjx \
        --discovery-token-ca-cert-hash sha256:d97f7536e4d82820b54edc79b83f8d010314b678038a0145867cb3f024cc0409
